name: "Multi Event Pipeline"

on:
    push:
        branches:
            - Master
    
    pull_request:
        branches:
            - main
        types:
            - closed
    workflow_dispatch:

jobs:
    on-push:
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on master push"
              run: echo "Running on master push"
    
    on-pull_request:
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps:
            - name: "Pull request on main"
              run: echo "Pull request on main"
    
    on-pull_request_types:
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        runs-on: ubuntu-latest
        steps:
            - name: "Pull request is closed"
              run: echo "Pull request closed"
    
    on-workflow_dispatch:
        if: github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest
        steps:
            - name: "Workflow dispatch"
              run: echo "Workflow dispatch"
